#pragma once

#define LF_TARGET_OS LF_OS_FREERTOS
#define LF_THREADING
#define LF_NEWLIB_TO_RTOS_MALLOC
#define LF_TERMINAL_STREAM_USART_STM32
#define LF_USB_DEVICE
#define CMSIS_DEVICE_FILE "stm32f7xx.h"
#define LF_TARGET_OS LF_OS_FREERTOS